id: "Test"
gameAddress: "localhost"
gameAddressPort: -1 # A negative value will be replaced by the game port of the server. This can be used when outgoing ports are different from internal ones.
type: "Test"
onlineJoinable: true
playersJoinable: true
playingJoinable: true
maxOnlineSlots: -1
maxPlayersSlots: -1
maxPlayingSlots: -1
onlineKickable: true
playersKickable: true
playingKickable: true
isPrivate: false

connection:
  port: 7766
  ip: "localhost"
  # Currently, only SOCKET is supported
  type: "SOCKET"
  socket:
    ssl: true